# Generated by Django 5.0.4 on 2024-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Doctor Appointment System', max_length=100)),
                ('favicon', models.ImageField(default='images/favicon.ico', upload_to='images/')),
                ('logo_image', models.ImageField(default='images/manas.jpg', upload_to='images/')),
                ('home_image', models.ImageField(default='images/doctor.jpg', upload_to='images/')),
                ('about_image', models.ImageField(default='images/about.jpg', upload_to='images/')),
                ('teeth_image', models.ImageField(default='images/teeth.jpeg', upload_to='images/')),
                ('faq_image', models.ImageField(default='images/faq.png', upload_to='images/')),
                ('address_line1', models.CharField(default='S.G Palya, Koramangala', max_length=255)),
                ('address_line2', models.CharField(default='Bangalore, Karnataka', max_length=255)),
                ('phone_number', models.CharField(default='+91 9234123456', max_length=20)),
                ('email', models.EmailField(default='axyz10649@gmail.com', max_length=254)),
                ('copyright_text', models.CharField(default='copyrigt@Soumyaranjan Pandua', max_length=255)),
                ('about_text', models.TextField(default='We are dedicated to providing the best healthcare services to our patients. Our team of experienced doctors is here to ensure your well-being and health.')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
