# Generated by Django 5.0.4 on 2024-08-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_faq_faq_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='faq_image',
        ),
    ]
