# Generated by Django 5.0.4 on 2024-08-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_doctor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_patient',
            field=models.BooleanField(default=True),
        ),
    ]
