# Generated by Django 5.0.4 on 2024-09-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_doctorprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_active',
        ),
    ]
