# Generated by Django 5.0.4 on 2024-08-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_adminprofile_is_admin_doctorprofile_is_doctor_and_more'),
        ('doctorapp', '0003_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('apt_no', models.AutoField(primary_key=True, serialize=False)),
                ('apt_date', models.DateField()),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_comment', models.TextField(blank=True, null=True)),
                ('doctor_comment', models.TextField(blank=True, null=True)),
                ('consultation_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=20)),
                ('consultation_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.patientprofile')),
            ],
        ),
    ]
