# Generated by Django 5.0.4 on 2024-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apt_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
